# docker-compose.yml

version: '3'

services:
  app:
    image: node:10.15.0
    command: bash -c "npm install && npm start"
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - realtime
    ports:
      - "80:3000"
  realtime:
    image: supabase/realtime
    ports:
      - "4000:4000"
    env_file: .env.sample
    depends_on:
      - db
  rest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    env_file: .env.sample
    depends_on:
      - db
  db:
    image: supabase/packaged
    command: postgres -c wal_level=logical # Start with streaming enabled
    ports:
      - "6543:5432" # Use 6543 to avoid host port collisions
    env_file: .env.sample
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
